# Author: Vlad Niculae <vlad@vene.ro>
# License: BSD 3-clause

# interpretation of fields from Penn Discourse Treebank file format

PDTB_FIELDS = [
    'reltype',
    'section',
    'file',
    'conn_span',
    'conn_gorn_addr',
    'conn_raw',
    'position',
    'sent_no',
    'head',
    'conn1',
    'conn2',
    'sem_cls_1_1',
    'sem_cls_1_2',
    'sem_cls_2_1',
    'sem_cls_2_2',
    'rel_source',
    'rel_type',
    'rel_polarity',
    'rel_determinacy',
    'rel_span',
    'rel_gorn_addr',
    'rel_raw',
    'arg1_span',
    'arg1_gorn_addr',
    'arg1_raw',
    'arg1_source',
    'arg1_type',
    'arg1_polarity',
    'arg1_determinacy',
    'arg1_attr_span',
    'arg1_attr_gorn_addr',
    'arg1_attr_raw',
    'arg2_span',
    'arg2_gorn_addr',
    'arg2_raw',
    'arg2_source',
    'arg2_type',
    'arg2_polarity',
    'arg2_determinacy',
    'arg2_attr_span',
    'arg2_attr_gorn_addr',
    'arg2_attr_raw',
    'sup1_span',
    'sup1_gorn_addr',
    'sup1_raw',
    'sup2_span',
    'sup2_gorn_addr',
    'sup2_raw',
]
